export type Media = {
  _id: string,
  name: string,
  slug: string,
  poster: string,
  releaseDate: number,
  chronologicalOrder: number,
  description: string,
  playLink: string,
  playLinkIcon?: string,
  trailerLink: string,
  relatedMedia: string[],
  duration: number,
  type: string,
  season?: number,
}